In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import make_classification
X, y =make_classification( n_samples=100,n_features=20,n_clusters_per_class=2,random_state=12)

In [3]:
X

array([[-0.6278858 ,  1.16433431, -0.70260271, ...,  2.12938724,
         1.87674122, -0.01896833],
       [-1.31728116, -1.37556573, -0.34490421, ..., -0.78402586,
         0.6275781 ,  1.58588983],
       [ 2.19601198,  1.13572008,  0.52890438, ...,  0.77543503,
         1.51745015,  0.62311449],
       ...,
       [ 1.35273335, -0.31045576, -0.32439472, ..., -1.24216027,
        -0.84297268,  1.05271316],
       [-0.10204558, -0.35652414, -0.21095559, ...,  1.21420518,
        -1.90981024,  0.56599786],
       [-0.97361671, -1.37308573, -1.11420114, ..., -0.68548419,
         0.75781968,  0.86110751]])

In [4]:
y

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1])

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X ,y,test_size= 0.3,random_state=42)

In [6]:
X_train.shape

(70, 20)

In [7]:
X_test.shape

(30, 20)

In [9]:
from sklearn.svm import SVC
classifier =SVC()
classifier.fit(X_train ,y_train)

SVC()

In [10]:
y_pred =classifier.predict(X_test)
y_pred

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1])

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test ,y_pred))
print(accuracy_score(y_test ,y_pred))
print(classification_report(y_test ,y_pred))

[[11  5]
 [ 1 13]]
0.8
              precision    recall  f1-score   support

           0       0.92      0.69      0.79        16
           1       0.72      0.93      0.81        14

    accuracy                           0.80        30
   macro avg       0.82      0.81      0.80        30
weighted avg       0.83      0.80      0.80        30



In [16]:
from sklearn.model_selection import GridSearchCV

param ={"kernel":["linear"],
       "C":[1,2,3,4,5,6],
       "gamma":[1,2,3,4,5]}
clf =SVC()

In [17]:
grid_clf =GridSearchCV(estimator=clf ,param_grid=param ,cv=5)
grid_clf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5, 6], 'gamma': [1, 2, 3, 4, 5],
                         'kernel': ['linear']})

In [18]:
grid_clf.fit(X_train ,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5, 6], 'gamma': [1, 2, 3, 4, 5],
                         'kernel': ['linear']})

In [19]:
grid_clf.best_estimator_

SVC(C=1, gamma=1, kernel='linear')

In [20]:
grid_clf.best_score_

0.8714285714285713

In [31]:
classify =SVC(C=1, gamma=1, kernel='linear')
classify.fit(X_train ,y_train)

SVC(C=1, gamma=1, kernel='linear')

In [32]:
y_classify_pred =classify.predict(X_test)

In [33]:
print(accuracy_score(y_test ,y_classify_pred))

0.8
