In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [4]:
from sklearn.datasets import make_regression
X,y =make_regression(random_state=1213)

In [5]:
X

array([[ 1.00289664, -0.69659831, -1.57543447, ...,  0.08899368,
         0.91187991, -0.45018854],
       [ 1.504318  ,  1.14351027,  1.63969734, ...,  0.74259147,
        -1.47379229,  0.85850658],
       [ 0.09148216,  1.75133304,  1.51881907, ...,  1.56637305,
        -0.32153108,  0.14595535],
       ...,
       [-0.38772854, -0.0064616 , -0.12383814, ..., -1.16602499,
         1.39476745, -0.09490248],
       [-2.93810928,  0.08397834, -0.36459888, ..., -0.21980916,
         0.19179486, -0.7241325 ],
       [-0.05472573, -0.48107427, -0.9674479 , ..., -0.02332646,
        -0.93927037, -0.7755776 ]])

In [6]:
y

array([-300.23518147,   95.32418222,  -37.73108111,  320.81652552,
        121.04899385,   85.99647091,  -68.75530592,  384.91261377,
         -5.63174169,   71.67504988,   84.08289225, -235.29037893,
        156.71540282, -314.51747167, -216.45092685,  -83.40366475,
       -151.40260371,  -18.25473576, -124.97683382,  -61.61462364,
       -409.77669199,   64.0603723 ,   80.6467855 ,  -95.62947588,
        134.06237351,   49.94620442,  129.79810455,  381.99934586,
        145.10865698,    3.39414962,   36.79009669,  210.08130204,
        227.09945548,    2.8100783 ,  200.31625871, -126.45309122,
        -90.58415095, -123.09029273,  160.8000727 ,  -83.24590567,
        105.60922294,   62.5326177 ,  330.4604766 , -131.15926194,
        307.96434609,  161.54213381,  -49.1494534 ,  281.50337074,
       -122.19493585,  105.49089845,  117.10290842,  248.71255136,
        143.18286277,    1.73894375,  263.69125612,  307.78560309,
        -86.34026961,  411.2476516 ,  -83.41425974,   85.11431

In [8]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X ,y,test_size=0.28 ,random_state=1232)

In [9]:
X_train

array([[ 0.66970164,  0.93232074, -0.08176006, ..., -0.84398251,
         0.08929295, -0.32878041],
       [ 0.54572897, -0.82950534, -1.08740431, ..., -0.17981916,
        -0.23214481, -1.78781635],
       [ 1.34154753, -0.2050059 , -0.86082113, ..., -0.03264186,
         1.88148416,  0.41376264],
       ...,
       [ 1.77983199,  0.13782692,  1.63586546, ...,  0.19070517,
        -1.00239149, -0.81376551],
       [-0.37907416,  0.52191   , -1.2726915 , ...,  1.64853234,
        -1.22618756,  0.46921711],
       [ 1.1003346 ,  0.31668164,  1.6844217 , ..., -0.18923935,
        -0.28492996,  0.98703058]])

In [10]:
y_test

array([-216.45092685, -117.94829485,  287.07760739,   71.67504988,
        134.06237351, -131.15926194, -235.29037893,   36.79009669,
         80.6467855 ,  -43.82684632,   -5.63174169, -126.45309122,
        307.78560309,   84.08289225,  -18.25473576, -151.40260371,
         62.5326177 ,  210.23969173,  320.81652552,  281.50337074,
          4.38793914,  117.26728906,  307.96434609,  145.10865698,
        381.99934586, -123.09029273,  330.4604766 ,  411.2476516 ,
        105.49089845])

In [11]:
from sklearn.svm import SVR
regressor =SVR()
regressor

SVR()

In [12]:
regressor.fit(X_train,y_train)
y_pred =regressor.predict(X_test)
y_pred

array([18.15109278, 18.18009658, 18.57474552, 18.03067201, 18.7217714 ,
       18.3476204 , 18.29709988, 18.31598248, 18.61106216, 18.08871734,
       18.47322713, 18.15563763, 18.58091908, 18.53398944, 18.17495374,
       18.50548746, 18.25041599, 18.35526776, 18.77236652, 18.962404  ,
       18.85059357, 18.58252921, 18.77963194, 18.73717161, 18.71731408,
       18.27034131, 18.50732617, 18.84541024, 18.48708125])

In [13]:
from sklearn.metrics import r2_score,mean_squared_error

print(mean_squared_error(y_test ,y_pred))

38463.9932378369


In [14]:
print(r2_score(y_test ,y_pred))

-0.13513757490391032


In [17]:
from sklearn.model_selection import GridSearchCV
parameter ={"kernel":["linear","poly","rbf","sigmoid"],
           "gamma":["scale","auto"],
           "C":[1,2,3,4,5],
           "epsilon":[1,2,3,4,5,6,7,8,9]}
regressor_svr =SVR()

In [18]:
regressors =GridSearchCV(estimator=regressor_svr ,param_grid=parameter)
regressors.fit(X_train ,y_train)

GridSearchCV(estimator=SVR(),
             param_grid={'C': [1, 2, 3, 4, 5],
                         'epsilon': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [19]:
regressors.best_estimator_

SVR(C=5, epsilon=9, kernel='linear')

In [20]:
regressors.best_score_

0.4869811272425569

In [21]:
regressors.best_params_

{'C': 5, 'epsilon': 9, 'gamma': 'scale', 'kernel': 'linear'}