In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
from sklearn.datasets import load_diabetes
X ,y =load_diabetes(return_X_y=True)

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.3,random_state=42)

In [8]:
X_train.shape

(309, 10)

In [9]:
X_test.shape

(133, 10)

In [11]:
from sklearn.svm import SVR
regressor =SVR()
regressor.fit(X_train ,y_train)

SVR()

In [12]:
y_pred =regressor.predict(X_test)
y_pred

array([142.45373634, 143.02422302, 141.43899361, 152.20312414,
       137.14186829, 134.88912605, 154.51552628, 150.76640816,
       130.00756822, 132.52109603, 126.91537109, 139.17968373,
       127.91679814, 157.05940002, 126.31194254, 132.1791542 ,
       158.07199055, 159.36991159, 143.06469992, 158.73208634,
       146.5353432 , 128.53414979, 121.96083577, 152.8029102 ,
       136.25903599, 143.71671539, 148.97983089, 145.42857291,
       123.86482009, 133.45836495, 145.81926692, 130.80899723,
       134.04045045, 150.51505854, 145.61981387, 147.60978799,
       132.24530273, 136.51839982, 146.27498195, 121.36639581,
       124.85360319, 132.18766591, 140.06718181, 144.94684904,
       144.37522297, 124.9600595 , 127.85987207, 131.1088166 ,
       121.6742027 , 136.46189797, 136.38373667, 127.88970213,
       138.76249138, 123.95829033, 146.71713372, 137.35935165,
       127.48171305, 150.75378896, 124.81149701, 130.19537977,
       149.31317839, 147.10217532, 133.01701073, 132.00

In [13]:
from sklearn.metrics import r2_score,mean_squared_error
print(mean_squared_error(y_test ,y_pred))

4525.810199575825


In [14]:
print(r2_score(y_test ,y_pred))

0.1616242720487805
